import { Box, Columns, Column, FlagIcon, Text, Link } from "@canva/app-ui-kit";
import { requestOpenExternalUrl } from "@canva/platform";
import { APP_NAME } from "src/config";

const REPORT_URL = `https://www.canva.com/help/report-content/?app=${APP_NAME}`;

/**
 * Component to display a box prompting users to report potentially inappropriate content generated by AI.
 * Providing users with a way to report inappropriate content is essential for maintaining a safe and respectful environment.
 */
export const ReportBox = (): JSX.Element => {
  const openExternalUrl = async (url: string) => {
    await requestOpenExternalUrl({
      url,
    });
  };

  return (
    <Box padding="2u" background="neutralLow" borderRadius="standard">
      <Columns spacing="1.5u" alignY="center">
        <Column width="content">
          <FlagIcon />
        </Column>
        <Column>
          <Text alignment="start">
            We’re evolving this new technology with you so please{" "}
            <Link
              href={REPORT_URL}
              requestOpenExternalUrl={() => openExternalUrl(REPORT_URL)}
              title="AI Product Terms"
            >
              report these images
            </Link>{" "}
            if they don’t seem right.
          </Text>
        </Column>
      </Columns>
    </Box>
  );
};
